const {onCall, HttpsError} = require("firebase-functions/v2/https");

const API_KEY ="AIzaSyAezpb1hEO4eQEUcl-6PanNXMHvWv3bcI4";

const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAI = new GoogleGenerativeAI(API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

exports.cloudFnGetImageDescription = onCall(cloudFnGetImageDescription);
async function cloudFnGetImageDescription(request, context) {
    // call gemini api to ectract image information
    //check for authentication
    if(!context.auth){
        throw new FirebaseFunctionsTest.https.HttpsError('unauthenticated', 'You must be autheticated to use this function');
    }
    const imageURL = request.data;
    // console => terminal of vscode
    console.log('cloud function: getImageDescripition', imageURL);

    return "image description generated by gemeni api";

    
}

